/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basededatos;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author lio
 */
public class AgregarValores extends javax.swing.JFrame {
    manejoDeArchivos manejo = new manejoDeArchivos();
    String atributo;
    String tipo;
    String tamaño;
    /**
     * Creates new form AgregarValores
     */
    public AgregarValores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGuardarDatos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDatos = new javax.swing.JTextArea();
        botonLeer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonGuardarDatos.setText("Agregar");
        botonGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarDatosActionPerformed(evt);
            }
        });

        textDatos.setColumns(20);
        textDatos.setRows(5);
        jScrollPane1.setViewportView(textDatos);

        botonLeer.setText("Leer");
        botonLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLeerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonLeer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonGuardarDatos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardarDatos)
                    .addComponent(botonLeer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarDatosActionPerformed
        String primerLinea,primerLinea2,primerLinea3;
        String palabraActual;
        int tokens=0;
        int atributoCounter = 0;

        try {
            // TODO add your handling code here:
            BufferedReader bufferedReader = new BufferedReader (new FileReader ("/home/lio/Code/BasesDeDatos/Articulo.txt"));

            primerLinea = bufferedReader.readLine();
            
            StringTokenizer stringTokenizer = new StringTokenizer(primerLinea, "@");
            while (stringTokenizer.hasMoreTokens()){
                if(tokens == 0){
                    String obtenerValor;
                    palabraActual = stringTokenizer.nextToken();
                    atributo = palabraActual;
                    System.out.println("Escribre valor para " +atributo);
                    Scanner leer = new Scanner(System.in);
                    obtenerValor = String.valueOf(leer.nextLine())+"@";
                    File archivo = new File("/home/lio/Code/BasesDeDatos/AlumnoDatos.txt");
                    FileWriter escribir = new FileWriter(archivo, true);
                    escribir.write(obtenerValor);
                    escribir.close();
                    //System.out.println("valor de "+atributo+" Es "+obtenerValor);
                    //String s1 = "labelAtributo"+atributoCounter;
                    //System.out.println("Atributo"+atributo+atributoCounter);
                    atributoCounter ++;
                }if(tokens == 1){
                    palabraActual = stringTokenizer.nextToken();
                    tipo = palabraActual;
                    System.out.println("Tipo"+tipo);
                }if(tokens == 2){
                    palabraActual = stringTokenizer.nextToken();
                    tamaño = palabraActual;
                    System.out.println("Tam"+tamaño);
                    tokens = -1;
                }
                tokens++;
            //System.out.println ("    Palabra " + tokens + " es: " + s2);
        }
            BufferedReader bufferedReader2 = new BufferedReader (new FileReader ("/home/lio/Code/BasesDeDatos/Vendedor.txt"));

            primerLinea2 = bufferedReader2.readLine();
            StringTokenizer stringTokenizer2 = new StringTokenizer(primerLinea2, "@");
            while (stringTokenizer2.hasMoreTokens()){
                if(tokens == 0){
                    String obtenerValor;
                    palabraActual = stringTokenizer2.nextToken();
                    atributo = palabraActual;
                    System.out.println("Escribre valor para " +atributo);
                    Scanner leer = new Scanner(System.in);
                    obtenerValor = String.valueOf(leer.nextLine())+"@";
                    File archivo = new File("/home/lio/Code/BasesDeDatos/AlumnoDatos.txt");
                    FileWriter escribir = new FileWriter(archivo, true);
                    escribir.write(obtenerValor);
                    escribir.close();
                    //System.out.println("valor de "+atributo+" Es "+obtenerValor);
                    //String s1 = "labelAtributo"+atributoCounter;
                    //System.out.println("Atributo"+atributo+atributoCounter);
                    atributoCounter ++;
                }if(tokens == 1){
                    palabraActual = stringTokenizer2.nextToken();
                    tipo = palabraActual;
                    System.out.println("Tipo"+tipo);
                }if(tokens == 2){
                    palabraActual = stringTokenizer2.nextToken();
                    tamaño = palabraActual;
                    System.out.println("Tam"+tamaño);
                    tokens = -1;
                }
                tokens++;
            //System.out.println ("    Palabra " + tokens + " es: " + s2);
            }
            BufferedReader bufferedReader3 = new BufferedReader (new FileReader ("/home/lio/Code/BasesDeDatos/Ventas.txt"));

            primerLinea3 = bufferedReader3.readLine();
            StringTokenizer stringTokenizer3 = new StringTokenizer(primerLinea3, "@");
            while (stringTokenizer3.hasMoreTokens()){
                if(tokens == 0){
                    String obtenerValor;
                    palabraActual = stringTokenizer3.nextToken();
                    atributo = palabraActual;
                    System.out.println("Escribre valor para " +atributo);
                    Scanner leer = new Scanner(System.in);
                    obtenerValor = String.valueOf(leer.nextLine())+"@";
                    File archivo = new File("/home/lio/Code/BasesDeDatos/AlumnoDatos.txt");
                    FileWriter escribir = new FileWriter(archivo, true);
                    escribir.write(obtenerValor);
                    escribir.close();
                    //System.out.println("valor de "+atributo+" Es "+obtenerValor);
                    //String s1 = "labelAtributo"+atributoCounter;
                    //System.out.println("Atributo"+atributo+atributoCounter);
                    atributoCounter ++;
                }if(tokens == 1){
                    palabraActual = stringTokenizer3.nextToken();
                    tipo = palabraActual;
                    System.out.println("Tipo"+tipo);
                }if(tokens == 2){
                    palabraActual = stringTokenizer3.nextToken();
                    tamaño = palabraActual;
                    System.out.println("Tam"+tamaño);
                    tokens = -1;
                }
                tokens++;
            //System.out.println ("    Palabra " + tokens + " es: " + s2);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AgregarValores.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AgregarValores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonGuardarDatosActionPerformed

    private void botonLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLeerActionPerformed
        // TODO add your handling code here:
        manejo.leerArchivoCompleto(textDatos);
    }//GEN-LAST:event_botonLeerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarValores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarDatos;
    private javax.swing.JButton botonLeer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textDatos;
    // End of variables declaration//GEN-END:variables
}
